require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - config/**/*
    - spec/support/shared_contexts/when_user_signed_in.rb

Rails/NotNullColumn:
  Enabled: false

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 45

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
